#! /bin/bash

echo "Iniciado o job"

mkdir /adm
mkdir /sec
mkdir /ven
mkdir /publico

groupadd GRP_ADM
groupadd GRP_VEN
groupadd GRP_SEC

useradd carlos -c "carlinhos" -m -s /bin/bash -p $(openssl passwd -1 Senha123) -G GRP_ADM
useradd maria -c "ma" -m -s /bin/bash -p $(openssl passwd -1 Senha123) -G GRP_ADM 
useradd joao -c "jao" -m -s /bin/bash -p $(openssl passwd -1 Senha123) -G GRP_ADM 
useradd debora -c "deb" -m -s /bin/bash -p $(openssl passwd -1 Senha123) -G GRP_VEN
useradd sebastiana -c "ana" -m -s /bin/bash -p $(openssl passwd -1 Senha123) -G GRP_VEN
useradd roberto -c "bebeto" -m -s /bin/bash -p $(openssl passwd -1 Senha123) -G GRP_VEN
useradd amanda -c "amandinha" -m -s /bin/bash -p $(openssl passwd -1 Senha123) -G GRP_SEC
useradd josefina -c "jose" -m -s /bin/bash -p $(openssl passwd -1 Senha123) -G GRP_SEC
useradd rogerio -c "rogerin" -m -s /bin/bash -p $(openssl passwd -1 Senha123) -G GRP_SEC

chown root:root /publico
chown root:GRP_ADM /adm
chown root:GRP_VEN /ven
chown root:GRP_SEC /sec

chmod 777 /publico
chmod 770 /adm
chmod 770 /ven
chmod 770 /sec
